# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    secret: '%env(APP_SECRET)%'
    sincro_files: 'public/uploads/sincro'
    sincro_uploads: '%kernel.project_dir%/%sincro_files%'
    sincro_downloads: '%router.request_context.scheme%://%router.request_context.host%/%sincro_files%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Application\Service\Sincro\GetSincroService:
        public: true
        arguments:
            $uploadsDir: '%sincro_uploads%'

    App\Application\Service\Sincro\PostSincroService:
        public: true
        arguments:
            $uploadsDir: '%sincro_uploads%'

    App\Application\Service\Sincro\PutSincroService:
        public: true
        arguments:
            $uploadsDir: '%sincro_uploads%'

    App\Application\Service\Sincro\ViewSincroService:
        public: true
        arguments:
            $uploadsDir: '%sincro_uploads%'

    App\Application\Service\Sincro\SincroResponse:
        public: true
        arguments:
            $uploadsDir: '%sincro_uploads%'
            $downloadBaseUrl: '%sincro_downloads%'

    App\Application\Service\Security\TokenValidator:
        public: true
        arguments:
            $secret: '%secret%'